maintenance:
  timings:
    - startTime: "09:00"
      endTime: "09:15"
    - startTime: "13:00"
      endTime: "13:15"
    - startTime: "17:00"
      endTime: "17:15"


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui